name: fl_channel
description: channel for native communication,Support ios macos android only
version: 0.0.1
repository: https://github.com/Wayaer/fl_channel.git

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.channel
        pluginClass: FlChannelPlugin
      ios:
        pluginClass: FlChannelPlugin
      macos:
        pluginClass: FlChannelPlugin
