name: fl_channel
description: channel for native communication,Support ios macos android only
version: 0.2.0
repository: https://github.com/Wayaer/fl_channel.git

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: fl.channel
        pluginClass: FlChannelPlugin
      ios:
        pluginClass: FlChannelPlugin
      macos:
        pluginClass: FlChannelPlugin
